name: World1-6FireAlarms
version: 1.0
main: com.andrew121410.mc.world16firealarms.World16FireAlarms
api-version: 1.16
authors: [Andrew121410]
description: A fire alarm plugin that i made for a private mc server

depend:
  - World1-6Utils

commands:
  firealarm:
    permission: world16firealarms.firealarm
    description: lets you do the the firealarm command

permissions:
  world16firealarms.firealarm:
    description: lets you do the firealarm command