name: World1-6FireAlarms
version: ${project.version}
main: com.andrew121410.mc.world16firealarms.Main
api-version: 1.15
authors: [Andrew121410]
description: A fire alarm plugin that i made for a private mc server

commands:
  firealarm:
    permission: world16firealarms.firealarm
    description: lets you do the the firealarm command

permissions:
  world16firealarms.firealarm:
    description: lets you do the firealarm command